import type { GloryaEvaluatedNeed } from './types';

/**
 * Illustrative evaluated-need layer for instrument design.
 * Coordinates are real city/locality WGS84 positions.
 * These are not live allocations — evaluation-only until the
 * $1M Solace revenue gate and a first sealed disbursement.
 */
export const gloryaEvaluatedNeeds: GloryaEvaluatedNeed[] = [
  {
    id: 'GLY-EV-001',
    city: 'Ouagadougou',
    country: 'Burkina Faso',
    lat: 12.3714,
    lon: -1.5197,
    needScore: 0.86,
    status: 'standing_down',
    focus: 'education',
    regime: 'Insecurity · seasonal access constraints',
    note: 'Primary schooling need is high; regime gate did not clear. No capital path.',
  },
  {
    id: 'GLY-EV-002',
    city: 'Goma',
    country: 'DR Congo',
    lat: -1.6777,
    lon: 29.2285,
    needScore: 0.74,
    status: 'evaluated',
    focus: 'education',
    regime: 'Moderate governance · partner review open',
    note: 'Literacy and school access evaluated. Commitment gate open for design review only.',
  },
  {
    id: 'GLY-EV-003',
    city: 'Cusco',
    country: 'Peru',
    lat: -13.5319,
    lon: -71.9675,
    needScore: 0.69,
    status: 'standing_down',
    focus: 'health',
    regime: 'Highland access · delivery window closed',
    note: 'Rural clinic access need recorded; timing gate failed. Unfunded on the map.',
  },
  {
    id: 'GLY-EV-004',
    city: 'Chattogram',
    country: 'Bangladesh',
    lat: 22.3569,
    lon: 91.7832,
    needScore: 0.81,
    status: 'evaluated',
    focus: 'education',
    regime: 'Cyclone season · partner capacity pending',
    note: 'Coastal school need is verifiable. Allocation dormant until instrument activation.',
  },
  {
    id: 'GLY-EV-005',
    city: 'Jijiga',
    country: 'Ethiopia',
    lat: 9.35,
    lon: 42.8,
    needScore: 0.91,
    status: 'standing_down',
    focus: 'water',
    regime: 'Conflict adjacency · verification incomplete',
    note: 'Water access severity high; environment not yet stable enough for deployment.',
  },
  {
    id: 'GLY-EV-006',
    city: 'Port-au-Prince',
    country: 'Haiti',
    lat: 18.5944,
    lon: -72.3074,
    needScore: 0.88,
    status: 'standing_down',
    focus: 'shelter',
    regime: 'Security · delivery corridor unstable',
    note: 'Shelter need clear; regime gate held. Standing down until path can carry intervention.',
  },
  {
    id: 'GLY-EV-007',
    city: 'Freetown',
    country: 'Sierra Leone',
    lat: 8.4657,
    lon: -13.2317,
    needScore: 0.72,
    status: 'evaluated',
    focus: 'health',
    regime: 'Stable enough · partner shortlist open',
    note: 'Clinic access evaluation on file. No disbursement until the revenue gate.',
  },
  {
    id: 'GLY-EV-008',
    city: 'Cox’s Bazar',
    country: 'Bangladesh',
    lat: 21.4272,
    lon: 92.0058,
    needScore: 0.84,
    status: 'evaluated',
    focus: 'protection',
    regime: 'Displacement context · verification design pending',
    note: 'Protection need evaluated at locality level. Instrument remains dormant.',
  },
  {
    id: 'GLY-EV-009',
    city: 'Maiduguri',
    country: 'Nigeria',
    lat: 11.8311,
    lon: 13.151,
    needScore: 0.89,
    status: 'standing_down',
    focus: 'nutrition',
    regime: 'Conflict-affected · access intermittent',
    note: 'Nutrition need severe; all three gates must clear before any path opens.',
  },
  {
    id: 'GLY-EV-010',
    city: 'Jalalabad',
    country: 'Afghanistan',
    lat: 34.4265,
    lon: 70.4515,
    needScore: 0.9,
    status: 'standing_down',
    focus: 'education',
    regime: 'High insecurity · partner verification incomplete',
    note: 'Need is real; regime and verification gates require stand-down.',
  },
  {
    id: 'GLY-EV-011',
    city: 'Aleppo',
    country: 'Syria',
    lat: 36.2021,
    lon: 37.1343,
    needScore: 0.87,
    status: 'standing_down',
    focus: 'shelter',
    regime: 'Active conflict adjacency',
    note: 'Evaluated and stood down. Empty capital path by design.',
  },
  {
    id: 'GLY-EV-012',
    city: 'Sana’a',
    country: 'Yemen',
    lat: 15.3694,
    lon: 44.191,
    needScore: 0.93,
    status: 'standing_down',
    focus: 'water',
    regime: 'Conflict · supply chain blocked',
    note: 'Highest-severity water need in the sample set; environment cannot yet carry intervention.',
  },
];

export function gloryaProcessScoreboard(needs: GloryaEvaluatedNeed[] = gloryaEvaluatedNeeds) {
  const evaluated = needs.length;
  const standingDown = needs.filter((n) => n.status === 'standing_down').length;
  const active = needs.filter((n) => n.status === 'active').length;
  const completed = needs.filter((n) => n.status === 'completed').length;

  return {
    evaluated,
    active,
    completed,
    standingDown,
    standDownRate: evaluated ? standingDown / evaluated : 0,
    calibration: null as number | null,
  };
}
